In [1]:
import numpy as np

1. [Матрицы и матричные операции. Часть 1](#matrix_p1)
    *  [Задание 1](#matrix_p1_1)
    *  [Задание 2](#matrix_p1_2)
    *  [Задание 3](#matrix_p1_3)
    *  [Задание 4](#matrix_p1_4)
    *  [Задание 5](#matrix_p1_5)
2. [Матрицы и матричные операции. Часть 2](#matrix_p2)
    *  [Задание 1](#matrix_p2_1)
    *  [Задание 2](#matrix_p2_2)
    *  [Задание 3](#matrix_p2_3)
    *  [Задание 4](#matrix_p2_4)

# Матрицы и матричные операции. Часть 1 <a class='anchor' id='matrix_p1'>

### Задание 1 <a class='anchor' id='matrix_p1_1'>

*Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:*

*а) $A$ — матрица $4 \times 2$, $B$ — матрица $4 \times 2$;*
    
*б) $A$ — матрица $2 \times 5$, $B$ — матрица $5 \times 3$;*

*в) $A$ — матрица $8 \times 3$, $B$ — матрица $3 \times 8$;*
    
*г) $A$ — квадратная матрица $4 \times 4$, $B$ — квадратная матрица $4 \times 4$.*

Матрицу $A$ можно умножить на матрицу $B$, если они согласованы, т.е. если число столбцов матрицы $A$ равно числу строк матрицы $B$.

а) $A$ — матрица $4 \times 2$, $B$ — матрица $4 \times 2$.

Произведение $AB$ не определено, т.к. число столбцов $A$ = 2, число строк $B$ = 4.

Произведение $BA$ не определено, т.к. число столбцов $B$ = 2, число строк $A$ = 4.

**Ответ: $AB$ - нет, $BA$ - нет.**

б) $A$ — матрица $2 \times 5$, $B$ — матрица $5 \times 3$.

Произведение $AB$ определено, т.к. число столбцов $A$ = 5, число строк $B$ = 5. Размерность результата $2 \times 3$.

Произведение $BA$ не определено, т.к. число столбцов $B$ = 3, число строк $A$ = 2.

**Ответ: $AB$ - да $2 \times 3$, $BA$ - нет.**

в) $A$ — матрица $8 \times 3$, $B$ — матрица $3 \times 8$.

Произведение $AB$ определено, т.к. число столбцов $A$ = 3, число строк $B$ = 3. Размерность результата $8 \times 8$.

Произведение $BA$ определено, т.к. число столбцов $B$ = 8, число строк $A$ = 8. Размерность результата $3 \times 3$.

**Ответ: $AB$ - да $8 \times 8$, $BA$ - да $3 \times 3$.**

г) $A$ — квадратная матрица $4 \times 4$, $B$ — квадратная матрица $4 \times 4$.

Произведения $AB$, $BA$ определены, т.к. обе матрицы квадратные одинаковой размерности. Размерность результата $4 \times 4$.

**Ответ: $AB$ - да $4 \times 4$, $BA$ - да $4 \times 4$.**

### Задание 2 <a class='anchor' id='matrix_p1_2'>

*Найдите сумму и произведение матриц*

$$A = \begin{pmatrix}
1 & -2 \\ 
3 & 0
\end{pmatrix}, \; B = \begin{pmatrix}
4 & -1 \\ 
0 & 5
\end{pmatrix}.$$

Сумма матриц

$$A + B = \begin{pmatrix}
1 & -2 \\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1 \\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 + 4 & -2 - 1 \\ 
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\ 
3 & 5
\end{pmatrix}.$$

Произведение матриц

$$A B = \begin{pmatrix}
1 & -2 \\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1 \\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\ 
3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}.$$

**Ответ:** $A + B = \begin{pmatrix}
5 & -3 \\ 
3 & 5
\end{pmatrix}$, $A B = \begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}$.

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A + B =\n{A + B}\n')
print(f'A * B =\n{np.dot(A, B)}')

A + B =
[[ 5 -3]
 [ 3  5]]

A * B =
[[  4 -11]
 [ 12  -3]]


### Задание 3 <a class='anchor' id='matrix_p1_3'>

*Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию*

$$3A - 2B + 4C$$

*для матриц*
    
$$A = \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix}, B = \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix}, C = \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix}.$$

Вычислим линейную комбинацию

$$3A - 2B + 4C = 3 \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix} - 2 \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix} + 4 \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21 \\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10 \\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16 \\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}.$$

**Ответ:** $3A - 2B + 4C = \begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$.

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'3A - 2B + 4C =\n{3 * A - 2 * B + 4 * C}\n')

3A - 2B + 4C =
[[ 11  -5]
 [  9 -12]]



### Задание 4 <a class='anchor' id='matrix_p1_4'>

*Дана матрица*

$$A = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3
\end{pmatrix}.$$
    
*Вычислите $AA^T$ и $A^TA$.*

Транспонированная матрица

$$A^T = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix}.$$

Вычислим произведения

$$AA^T = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3 \\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3 \\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}.$$

$$A^TA = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}.$$

**Ответ:** $A^T = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix}$, $AA^T = \begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$, $A^TA = \begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}$.

In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T

print(f'A^T =\n{A_T}\n')
print(f'A * A^T =\n{np.dot(A, A_T)}\n')
print(f'A^T * A =\n{np.dot(A_T, A)}\n')

A^T =
[[ 4  5  2]
 [ 1 -2  3]]

A * A^T =
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A^T * A =
[[45  0]
 [ 0 14]]



### Задание 5 <a class='anchor' id='matrix_p1_5'>

*Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.*

In [5]:
class Matrix:
    """
    Класс для описания объекта "матрица"
    """

    def __init__(self, data):
        """
        Конструктор класса
        :param data: [[a11, a12, a13], [a21, a22, a23], ... ] список строк, где каждая строка тоже список
        """
        # Множество всех размеров строк
        rows_sizes = set([len(row) for row in data])
        
        # Матрица определяется только в том случае, если все строки имеют одинаковое число элементов
        self.data = data if len(rows_sizes) == 1 else []

    def __str__(self):
        rows_str = ['\t'.join(map(str, row)) for row in self.data]
        return '\n'.join(rows_str)

    def __add__(self, other):
        if self.is_size_equal(other):
            result = [list(map(lambda x, y: x + y, self.data[i], other.data[i])) for i in range(len(self.data))]
            return Matrix(result)
        else:
            return None
    
    def __mul__(self, other):
        # Если матрицы не согласованы, то умножение не определено
        if self.columns_count != other.rows_count:
            return None
        
        self_rows = len(self.data)
        other_rows = len(other.data)
        other_columns = len(other.data[0])
        
        result = [[None for _ in range(other_columns)] for _ in range(self_rows)]
        for i in range(self_rows):
            for j in range(other_columns):       
                result[i][j] = sum(self.data[i][k] * other.data[k][j] for k in range(other_rows))
        return Matrix(result)

    @property
    def rows_count(self):
        return len(self.data)

    @property
    def columns_count(self):
        return len(self.data[0]) if self.data else 0
    
    def is_size_equal(self, other):
        """
        Определяет имеют ли матрицы одинаковое количество строк и столбцов
        :param other: объект класса Matrix
        :return: True, если матрицы имеют одинаковое количество строк и столбцов, иначе False
        """
        return self.rows_count == other.rows_count and self.columns_count == other.columns_count

In [6]:
# Проверим на примере задания 4
A = Matrix([[4, 1], [5, -2], [2, 3]])
A_T = Matrix([[4, 5, 2], [1, -2, 3]])

print(f'A = \n{A}\n')
print(f'A_T = \n{A_T}\n')

print(f'A + A =\n{A + A}\n')
print(f'A_T + A_T =\n{A_T + A_T}\n')
print(f'A * A_T =\n{A * A_T}\n')
print(f'A_T * A =\n{A_T * A}\n')

A = 
4	1
5	-2
2	3

A_T = 
4	5	2
1	-2	3

A + A =
8	2
10	-4
4	6

A_T + A_T =
8	10	4
2	-4	6

A * A_T =
17	18	11
18	29	4
11	4	13

A_T * A =
45	0
0	14



# Матрицы и матричные операции. Часть 2 <a class='anchor' id='matrix_p2'>

### Задание 1 <a class='anchor' id='matrix_p2_1'>

*Вычислите определитель:*

*a)* $\begin{vmatrix}
\sin x & -\cos x \\ 
\cos x & \sin x
\end{vmatrix};$

*б)* $\begin{vmatrix}
4 & 2 & 3 \\ 
0 & 5 & 1 \\ 
0 & 0 & 9
\end{vmatrix};$
    
*в)* $\begin{vmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{vmatrix}.$

a) $\begin{vmatrix}
\sin x & -\cos x \\ 
\cos x & \sin x
\end{vmatrix} = \sin^2 x + \cos^2 x = 1$.

**Ответ: 1.**

б) $\begin{vmatrix}
4 & 2 & 3 \\ 
0 & 5 & 1 \\ 
0 & 0 & 9
\end{vmatrix} = 4 \begin{vmatrix}
5 & 1 \\
0 & 9
\end{vmatrix} = 4(5 \cdot 9 - 1 \cdot 0) = 180$.

**Ответ: 180.**

в) $\begin{vmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{vmatrix} = 1 \begin{vmatrix}
5 & 6 \\
8 & 9
\end{vmatrix} - 2 \begin{vmatrix}
4 & 6 \\
7 & 9
\end{vmatrix} + 3 \begin{vmatrix}
4 & 5 \\
7 & 8
\end{vmatrix} = (45 - 48) - 2(36 - 42) + 3(32 - 35) = -3 + 12 - 9 = 0.$

**Ответ: 0.**

In [7]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'б) det A = {np.linalg.det(A)}')

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'в) det A = {np.linalg.det(A)}')

б) det A = 180.0
в) det A = 0.0


### Задание 2 <a class='anchor' id='matrix_p2_2'>

*Определитель матрицы $A$ равен $4$. Найдите:*

*а) $\det(A^2)$;*
    
*б) $\det(A^T)$;*
    
*в) $\det(2A)$.*

а) $\det(A^2)$.

По свойству определителя для двух квадратных матриц одинакового размера

$$\det (AB) = \det A \det B.$$

Тогда

$$\det (A^2) = (\det A)^2 = 16.$$

**Ответ: 16.**

б) $\det(A^T)$.

По свойству определитель транспонированной матрицы равен определителю исходной, поэтому

$$\det(A^T) = \det A = 4.$$

**Ответ: 4.**

в) $\det(2A)$.

По свойству определителя умножение строки на число приведет к умножению матрицы на то же число. По условию каждая строка матрицы умножается на два, тогда

$$\det(2A) = 2^n \det A = 4 \cdot 2^n,$$

где $n$ - размерность матрицы $A$.

**Ответ:** $4 \cdot 2^n.$

In [8]:
# Проверим на примере произвольной невырожденной матрицы размерности 3
A = np.array([[4, 0, 0], [0, 1, 0], [0, 0, 1]])

print(f'det A = {np.linalg.det(A)}')
print(f'dim A = {A.shape}\n')

print(f'а) det A^2 = {np.linalg.det(np.linalg.matrix_power(A, 2))}')
print(f'б) det A^T = {np.linalg.det(A.T)}')
print(f'в) det 2A = {np.linalg.det(2 * A)}')

det A = 4.0
dim A = (3, 3)

а) det A^2 = 15.999999999999998
б) det A^T = 4.0
в) det 2A = 32.0


### Задание 3 <a class='anchor' id='matrix_p2_3'>

*Докажите, что матрица:*

$$\begin{pmatrix}
-2 & 7 & -3 \\ 
4 & -14 & 6 \\ 
-3 & 7 & 13
\end{pmatrix}$$
   
*вырожденная.*

Матрица называется сингулярной или вырожденной, если её определитель равен нулю.

Первая и вторая строки этой матрицы линейно зависимы, поэтому определитель равен 0. Проверим это, вычислим определитель

$$\begin{vmatrix}
-2 & 7 & -3 \\ 
4 & -14 & 6 \\ 
-3 & 7 & 13
\end{vmatrix} = -2 \begin{vmatrix}
-14 & 6 \\
7 & 13
\end{vmatrix} - 7 \begin{vmatrix}
4 & 6 \\
-3 & 13
\end{vmatrix} - 3 \begin{vmatrix}
4 & -14 \\
-3 & 7
\end{vmatrix} = -2(-182 - 42) - 7(52 + 18) - 3(28 - 42) = 448 - 490 + 42 = 0.$$

**Ответ: Определитель равен 0, матрица вырожденная.**

### Задание 4 <a class='anchor' id='matrix_p2_4'>

*Найдите ранг матрицы:*

*а) $\begin{pmatrix}
1 & 2 & 3 \\ 
1 & 1 & 1 \\ 
2 & 3 & 4
\end{pmatrix};$*

*б) $\begin{pmatrix}
0 & 0 & 2 & 1 \\ 
0 & 0 & 2 & 2 \\ 
0 & 0 & 4 & 3 \\ 
2 & 3 & 5 & 6
\end{pmatrix}.$*

а) Найдем ранг матрицы

$$\begin{pmatrix}
1 & 2 & 3 \\ 
1 & 1 & 1 \\ 
2 & 3 & 4
\end{pmatrix}.$$

Вычтем из второй строки первую строку, а из третьей - первую строку, умноженную на 2, получим

$$\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
0 & -1 & -2
\end{pmatrix}.$$

Третья строка - линейная комбинация первых двух строк, поэтому ее можно отбросить, получим

$$\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -1 & -2 
\end{pmatrix}.$$

Таким образом ранг матрицы равен 2.

**Ответ: 2.**

б) Найдем ранг матрицы

$$\begin{pmatrix}
0 & 0 & 2 & 1 \\ 
0 & 0 & 2 & 2 \\ 
0 & 0 & 4 & 3 \\ 
2 & 3 & 5 & 6
\end{pmatrix}.$$

Переставим первую и четвертую строки местами

$$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 4 & 3 \\ 
0 & 0 & 2 & 1
\end{pmatrix}.$$

Вычтем из третьей строки вторую строку, умноженную на 2, а из четвертой - вторую строку получим

$$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & -1 \\ 
0 & 0 & 0 & -1
\end{pmatrix}.$$

Вычтем из четвертой строки третью, получим нулевую строку

$$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & -1 \\ 
0 & 0 & 0 & 0
\end{pmatrix}.$$

Нулевую строку можно отбросить

$$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & -1
\end{pmatrix}.$$

Таким образом ранг матрицы равен 3.

**Ответ: 3.**

In [9]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'а) rank A = {np.linalg.matrix_rank(A)}')

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'б) rank A = {np.linalg.matrix_rank(A)}')

а) rank A = 2
б) rank A = 3
