In [1]:
import numpy as np

1. [Системы линейных уравнений. Часть 1](#system_p1)
    *  [Задание 1](#system_p1_1)
    *  [Задание 2](#system_p1_2)
        *  [Пример 1](#system_p1_2_1)
        *  [Пример 2](#system_p1_2_2)
        *  [Пример 3](#system_p1_2_3)
    *  [Задание 3](#system_p1_3)
    *  [Задание 4](#system_p1_4)
2. [Системы линейных уравнений. Часть 2](#system_p2)
    *  [Задание 1](#system_p2_1)
        *  [Пример 1](#system_p2_1_1)
        *  [Пример 2](#system_p2_1_2)
    *  [Задание 2](#system_p2_2)
        *  [Пример 1](#system_p2_2_1)
        *  [Пример 2](#system_p2_2_2)
    *  [Задание 3](#system_p2_3)
    *  [Задание 4](#system_p2_4)
    *  [Задание 5](#system_p2_5)
        *  [Метод Холецкого](#cholesky)
        *  [LU-разложение](#lu)

# Системы линейных уравнений. Часть 1 <a class='anchor' id='system_p1'>

### Задание 1 <a class='anchor' id='system_p1_1'>

*Решите систему уравнений методом Гаусса:*

$$\begin{cases}
x_1 + x_2 - x_3 - 2x_4 = 0, \\
2x_1 + x_2 - x_3 + x_4 = -2, \\
x_1 + x_2 - 3x_3 + x_4 = 4.
\end{cases}$$

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1 
\end{matrix} \right|
\begin{matrix}
0 \\ 
-2 \\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований приведем матрицу к ступенчатому виду.

Выполним преобразования над строками $(2) - 2 \cdot (1)$, $(3) - (1)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3 
\end{matrix} \right|
\begin{matrix}
0 \\ 
-2 \\
4
\end{matrix}
\end{pmatrix}.$$

Система имеет бесконечное количество решений. Неизвестная $x_4 = C$ - свободный параметр. Выразим остальные неизвестные:

$$\begin{cases}
x_3 = \frac{3}{2}C - 2, \\
x_2 = 5C + \frac{3}{2}C - 2 + 2 = 5C + \frac{3}{2}C = \frac{13}{2}C, \\
x_1 = 2C + \frac{3}{2}C - 2 - \frac{13}{2}C = -3C - 2.
\end{cases}$$

Получили общее решение системы.

**Ответ: $\begin{pmatrix}
-3C - 2 \\ 
\frac{13}{2}C \\
\frac{3}{2}C - 2 \\
C
\end{pmatrix}$, где $C$ - произвольная постоянная.**

### Задание 2 <a class='anchor' id='system_p1_2'>

*Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:*

*а)* $\begin{cases}
3x_1 - x_2 + x_3 = 4, \\
2x_1 - 5x_2 - 3x_3 = -17, \\
x_1 + x_2 - x_3 = 0;
\end{cases}$
    
*б)* $\begin{cases}
2x_1 - 4x_2 + 6x_3 = 1, \\
x_1 - 2x_2 + 3x_3 = -2, \\
3x_1 - 6x_2 + 9x_3 = 5;
\end{cases}$
    
*в)* $\begin{cases}
x_1 + 2x_2 + 5x_3 = 4, \\
3x_1 + x_2 - 8x_3 = -2. 
\end{cases}$

#### Пример 1 <a class='anchor' id='system_p1_2_1'>
    
*Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:*

$$\begin{cases}
3x_1 - x_2 + x_3 = 4, \\
2x_1 - 5x_2 - 3x_3 = -17, \\
x_1 + x_2 - x_3 = 0.
\end{cases}$$

Запишем расширенную матрицу

$$\tilde{A} = \begin{pmatrix}
\left. \begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1 
\end{matrix} \right|
\begin{matrix}
4 \\ 
-17 \\
0
\end{matrix}
\end{pmatrix}$$

Столбцы исходной матрицы линейно независимы. Три линейно независимых вектора образуют в трехмерном пространстве базис и любой вектор можно выразить через линейную комбинацию базисных векторов единственным образом.

Таким образом, система совместна и имеет единственное решение.

Проверим с помощью теоремы Кронекера-Капелли. Путем элементарных преобразований приведем матрицу к ступенчатому виду.

Переставим первую и третью строки местами:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 \\
2 & -5 & -3 \\
3 & -1 & 1
\end{matrix} \right|
\begin{matrix}
0 \\
-17 \\
4
\end{matrix}
\end{pmatrix}$$

Выполним преобразования над строками $(2) - 2 \cdot (1)$, $(3) - 3 \cdot (1)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
0 & -4 & 4
\end{matrix} \right|
\begin{matrix}
0 \\
-17 \\
4
\end{matrix}
\end{pmatrix}$$

Третью строку разделим на 4 и поменяем местами со второй:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 \\
0 & -1 & 1 \\
0 & -7 & -1
\end{matrix} \right|
\begin{matrix}
0 \\
1 \\
-17
\end{matrix}
\end{pmatrix}$$

Выполним преобразование $(3) - 7 \cdot (2)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 \\
0 & -1 & 1 \\
0 & 0 & -8
\end{matrix} \right|
\begin{matrix}
0 \\
1 \\
-24
\end{matrix}
\end{pmatrix}$$

Видно, что ранг основной матрицы $A$ совпадает с рангом расширенной матрицы $\tilde{A}$ и равен числу неизвестных $n$

$$\text{rank} A = \text{rank} \tilde{A} = n = 3.$$

Тогда по теореме Кронекера-Капелли такая система совместна и определена, т.е. имеет единственное решение.

**Ответ: система совместна и имеет единственное решение.**

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_tilde = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 3
Ранг расширенной матрицы = 3


#### Пример 2 <a class='anchor' id='system_p1_2_2'>
    
*Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:*

$$\begin{cases}
2x_1 - 4x_2 + 6x_3 = 1, \\
x_1 - 2x_2 + 3x_3 = -2, \\
3x_1 - 6x_2 + 9x_3 = 5;
\end{cases}$$

Запишем расширенную матрицу

$$\tilde{A} = \begin{pmatrix}
\left. \begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9 
\end{matrix} \right|
\begin{matrix}
1 \\ 
-2 \\
5
\end{matrix}
\end{pmatrix}$$

Очевидно, что все столбцы исходной матрицы линейно зависимы. Это значит, что все три вектора лежат на одной прямой, то есть принадлежат некоторому одномерному линейному подпространству исходного трехмерного пространства.

Вектор правой части и столбцы исходной матрицы линейно независимы. Это значит, что вектор правой части не принадлежит линейному подпространству, то есть не лежит на этой прямой.

Таким образом, система несовместна.

Действительно, как уже показали, ранг исходной матрицы равен 1, а ранг расширенной матрицы равен 2. Покажем это также с помощью приведения матрицы к ступенчатому виду путем элементарных преобразований.

Переставим первую и вторую строки местами:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & -2 & 3 \\
2 & -4 & 6 \\ 
3 & -6 & 9 
\end{matrix} \right|
\begin{matrix}
-2 \\
1 \\
5
\end{matrix}
\end{pmatrix}$$

Выполним преобразования над строками $(2) - 2 \cdot (1)$, $(3) - 3 \cdot (1)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\ 
0 & 0 & 0 
\end{matrix} \right|
\begin{matrix}
-2 \\
5 \\
11
\end{matrix}
\end{pmatrix}$$

Выполнив преобразование $(3) - \frac{11}{5} \cdot (2)$ получим:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0
\end{matrix} \right|
\begin{matrix}
-2 \\
5
\end{matrix}
\end{pmatrix}$$

Видно, что ранг основной матрицы $A$ меньше ранга расширенной матрицы $\tilde{A}$

$$\text{rank} A = 1 < \text{rank} \tilde{A} = 2.$$

Тогда по теореме Кронекера-Капелли такая система несовместна.

**Ответ: система несовместна.**

In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_tilde = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 1
Ранг расширенной матрицы = 2


#### Пример 3 <a class='anchor' id='system_p1_2_3'>
    
*Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:*

$$\begin{cases}
x_1 + 2x_2 + 5x_3 = 4, \\
3x_1 + x_2 - 8x_3 = -2. 
\end{cases}$$

Запишем расширенную матрицу

$$\tilde{A} = \begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8 
\end{matrix} \right|
\begin{matrix}
4 \\ 
-2
\end{matrix}
\end{pmatrix}$$

Столбцы исходной матрицы линейно независимы. Значит, в двумерном пространстве любая пара столбцов может образовать базис, по которому единственным образом можно разложить любой вектор. Коэффициент при третьем векторе может принимать любое значение, поэтому решений системы будет бесконечно много.

Таким образом, система совместна и имеет бесконечное количество решений.

Проверим с помощью теоремы Кронекера-Капелли. Путем элементарных преобразований приведем матрицу к ступенчатому виду.

Выполним преобразование $(2) - 3 \cdot (1)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 5 \\ 
0 & -5 & -23 
\end{matrix} \right|
\begin{matrix}
4 \\ 
-14
\end{matrix}
\end{pmatrix}$$

Видно, что ранг основной матрицы $A$ совпадает с рангом расширенной матрицы $\tilde{A}$

$$\text{rank} A = \text{rank} \tilde{A} = 2 < n = 3.$$

Тогда по теореме Кронекера-Капелли такая система совместна и имеет бесконечное количество решений.

**Ответ: система совместна и имеет бесконечное количество решений.**

In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
A_tilde = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 2
Ранг расширенной матрицы = 2


### Задание 3 <a class='anchor' id='system_p1_3'>

*Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:*

$$\tilde{A} = \begin{pmatrix}
\left. \begin{matrix}
1 & 3 & -2 & 4 \\ 
0 & 5 & 0 & 1 \\ 
0 & 0 & 3 & 0 \\ 
0 & 0 & 0 & 2
\end{matrix} \right|
\begin{matrix}
3 \\ 
2 \\
4 \\
1
\end{matrix}
\end{pmatrix}.$$

Очевидно, ранг основной матрицы $A$ совпадает с рангом расширенной матрицы $\tilde{A}$ и равен числу неизвестных $n$

$$\text{rank} A = \text{rank} \tilde{A} = n = 4.$$

Тогда по теореме Кронекера-Капелли такая система совместна и определена, т.е. имеет единственное решение.

**Ответ: система совместна и имеет единственное решение.**

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_tilde = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 4
Ранг расширенной матрицы = 4


### Задание 4 <a class='anchor' id='system_p1_4'>

*Дана система линейных уравнений, заданная расширенной матрицей:*

$$\tilde{A} = \begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix} \right|
\begin{matrix}
a \\ 
b \\
c
\end{matrix}
\end{pmatrix}.$$

*Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.*

Приведем матрицу к ступенчатому виду с помощью элементарных преобразований.

Выполним преобразования $(2) - 4 \cdot (1)$, $(3) - 7 \cdot (1)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 3 \\ 
0 & -3 & -6 \\ 
0 & -6 & -12
\end{matrix} \right|
\begin{matrix}
a \\ 
b - 4a \\
c - 7a
\end{matrix}
\end{pmatrix}.$$

Разделим вторую строку на 3:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
0 & -6 & -12
\end{matrix} \right|
\begin{matrix}
a \\ 
\frac{b - 4a}{3} \\
c - 7a
\end{matrix}
\end{pmatrix}.$$

Выполним преобразование $(3) - 6 \cdot (2)$:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
0 & 0 & 0
\end{matrix} \right|
\begin{matrix}
a \\ 
\frac{b - 4a}{3} \\
c - 7a - 6 \left( \frac{b - 4a}{3} \right)
\end{matrix}
\end{pmatrix}.$$

Перепишем 

$$c - 7a - 6 \left( \frac{b - 4a}{3} \right) = c - 7a - 2b + 8a = a - 2b + c.$$

Если

$$a - 2b + c \neq 0,$$

то $\text{rank} A = 2 < \text{rank} \tilde{A} = 3$ и по теореме Кронекера-Капелли система будет несовместной.

**Ответ: при $a - 2b + c \neq 0$ система будет несовместной.**

# Системы линейных уравнений. Часть 2 <a class='anchor' id='system_p2'>

### Задание 1 <a class='anchor' id='system_p2_1'>

*Решите систему уравнений методом Крамера:*

*а)* $\begin{cases}
x_1 - 2x_2 = 1, \\
3x_1 - 4x_2 = 7.
\end{cases}$
    
*б)* $\begin{cases}
2x_1 - x_2 + 5x_3 = 10, \\
x_1 + x_2 - 3x_3 = -2, \\
2x_1 + 4x_2 + x_3 = 1.
\end{cases}$

#### Пример 1 <a class='anchor' id='system_p2_1_1'>
    
*Решите систему уравнений методом Крамера:*

$$\begin{cases}
x_1 - 2x_2 = 1, \\
3x_1 - 4x_2 = 7.
\end{cases}$$

Вычислим определитель матрицы

$$\det A = \begin{vmatrix}
1 & -2 \\ 
3 & -4
\end{vmatrix} = -4 + 6 = 2 \neq 0,$$

т.е. система совместна.

Вычислим определители $\det A_1$, $\det A_2$, получаемые заменой $i$-го столбца на вектор правой части.

$$\det A_1 = \begin{vmatrix}
1 & -2 \\ 
7 & -4
\end{vmatrix} = -4 + 14 = 10,$$

$$\det A_2 = \begin{vmatrix}
1 & 1 \\ 
3 & 7
\end{vmatrix} = 7 - 3 = 4.$$

Тогда по формуле Крамера получим решение:

$$x_1 = \frac{\det A_1}{\det A} = \frac{10}{2} = 5,$$

$$x_2 = \frac{\det A_2}{\det A} = \frac{4}{2} = 2.$$

**Ответ:** $\begin{pmatrix}
5 \\ 
2
\end{pmatrix}$.

In [6]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 1 -2]
 [ 3 -4]]

Вектор правой части b =
[1 7]

Решение x_numpy =
[5. 2.]


#### Пример 2 <a class='anchor' id='system_p2_1_2'>
    
*Решите систему уравнений методом Крамера:*

$$\begin{cases}
2x_1 - x_2 + 5x_3 = 10, \\
x_1 + x_2 - 3x_3 = -2, \\
2x_1 + 4x_2 + x_3 = 1.
\end{cases}$$

Вычислим определитель матрицы

$$\det A = \begin{vmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix} = 2 \begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
1 & -3 \\
2 & 1
\end{vmatrix} + 5 \begin{vmatrix}
1 & 1 \\
2 & 4
\end{vmatrix} = 2(1 + 12) + (1 + 6) + 5(4 - 2) = 43 \neq 0,$$

т.е. система совместна.

Вычислим определители $\det A_1$, $\det A_2$, $\det A_3$ получаемые заменой $i$-го столбца на вектор правой части.

$$\det A_1 = \begin{vmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix} = 10 \begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
-2 & -3 \\
1 & 1
\end{vmatrix} + 5 \begin{vmatrix}
-2 & 1 \\
1 & 4
\end{vmatrix} = 10(1 + 12) + (-2 + 3) + 5(-8 - 1) = 86,$$

$$\det A_2 = \begin{vmatrix}
2 & 10 & 5 \\ 
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix} = 2 \begin{vmatrix}
-2 & -3 \\
1 & 1
\end{vmatrix} - 10 \begin{vmatrix}
1 & -3 \\
2 & 1
\end{vmatrix} + 5 \begin{vmatrix}
1 & -2 \\
2 & 1
\end{vmatrix} = 2(-2 + 3) - 10(1 + 6) + 5(1 + 4) = -43,$$

$$\det A_3 = \begin{vmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix} = 2 \begin{vmatrix}
1 & -2 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
1 & -2 \\
2 & 1
\end{vmatrix} + 10 \begin{vmatrix}
1 & 1 \\
2 & 4
\end{vmatrix} = 2(1 + 8) + (1 + 4) + 10(4 - 2) = 43.$$

Тогда по формуле Крамера получим решение:

$$x_1 = \frac{\det A_1}{\det A} = \frac{86}{43} = 2,$$

$$x_2 = \frac{\det A_2}{\det A} = \frac{-43}{43} = -1,$$

$$x_3 = \frac{\det A_3}{\det A} = \frac{43}{43} = 1.$$

**Ответ:** $\begin{pmatrix}
2 \\ 
-1 \\
1
\end{pmatrix}$.

In [7]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

Вектор правой части b =
[10 -2  1]

Решение x_numpy =
[ 2. -1.  1.]


### Задание 2 <a class='anchor' id='system_p2_2'>

*Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:*

*а)* $\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix};$
    
*б)* $\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}.$

#### Пример 1 <a class='anchor' id='system_p2_2_1'>
    
*Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:*

$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}.$$

Выполним преобразования $(2) - 2 \cdot (1)$, $(3) - 3 \cdot (1)$. Матрица системы примет вид:

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},$$

а матрица $L$:

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$

Далее выполним $(3) - 4 \cdot (2)$. Получим искомые матрицы

$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$

**Ответ:** $L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$.

In [8]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])

print(f'A =\n{A}\n')
print(f'LU =\n{np.dot(L, U)}')

A =
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

LU =
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


#### Пример 2 <a class='anchor' id='system_p2_2_2'>
    
*Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:*

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}.$$

Выполним преобразования $(2) - 2 \cdot (1)$, $(3) - 3 \cdot (1)$, $(4) - 4 \cdot (1)$. Матрица системы примет вид:

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix},$$

а матрица $L$:

$$L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$$

Далее выполним $(3) - 5 \cdot (2)$, $(4) - 6 \cdot (2)$. Получим

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix},$$

а матрица $L$:

$$L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1
\end{pmatrix}.$$

Выполним $(4) - 7 \cdot (3)$. Получим искомые матрицы

$$U = \begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix},$$

$$L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}.$$

**Ответ:** $L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$.

In [9]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])

print(f'A =\n{A}\n')
print(f'LU =\n{np.dot(L, U)}')

A =
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

LU =
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


### Задание 3 <a class='anchor' id='system_p2_3'>

*Решите систему линейных уравнений методом $LU$-разложения:*

$$\begin{cases}
2x_1 + x_2 + 3x_3 = 1, \\
11x_1 + 7x_2 + 5x_3 = -6, \\
9x_1 + 8x_2 + 4x_3 = -5.
\end{cases}$$

Матрица системы и вектор правой части имеют вид:

$$A = \begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}, \; b = \begin{pmatrix}
1 \\ 
-6 \\ 
-5
\end{pmatrix}.$$

Выполним преобразования $(2) - \frac{11}{2} \cdot (1)$, $(3) - \frac{9}{2} \cdot (1)$. Матрица системы примет вид:

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix},$$

а матрица $L$:

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & l_{32} & 1
\end{pmatrix}.$$

Далее выполним $(3) - \frac{7}{3} \cdot (2)$. Получим искомые матрицы

$$U = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}.$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}.$$

Теперь решим систему

$$Ly = b,$$

$$\begin{cases}
y_1 = 1, \\
\frac{11}{2}y_1 + y_2 = -6, \\
\frac{9}{2}y_1 + \frac{7}{3}y_2 + y_3 = -5.
\end{cases} \; \Rightarrow \; \begin{cases}
y_1 = 1, \\
y_2 = -6 - \frac{11}{2}y_1 = -6 - \frac{11}{2} = -\frac{23}{2}, \\
y_3 = -5 - \frac{9}{2}y_1 - \frac{7}{3}y_2 = -5 - \frac{9}{2} + \frac{161}{6} = \frac{52}{3}.
\end{cases}$$

Получили:

$$\begin{cases}
y_1 = 1, \\
y_2 = -\frac{23}{2}, \\
y_3 = \frac{52}{3}.
\end{cases}$$

Затем решим систему

$$Ux = y,$$

$$\begin{cases}
2x_1 + x_2 + 3x_3 = 1, \\
\frac{3}{2}x_2 - \frac{23}{2}x_3 = -\frac{23}{2}, \\
\frac{52}{3}x_3 = \frac{52}{3}.
\end{cases} \; \Rightarrow \; \begin{cases}
x_3 = 1, \\
x_2 = \frac{2}{3} \left( -\frac{23}{2} + \frac{23}{2}x_3 \right) = \frac{2}{3} \left( -\frac{23}{2} + \frac{23}{2} \right) = 0, \\
x_1 = \frac{1}{2} (1 - x_2 - 3x_3) = \frac{1}{2} (1 - 0 - 3) = -1.
\end{cases}$$

Получили решение

$$\begin{cases}
x_1 = -1, \\
x_2 = 0, \\
x_3 = 1.
\end{cases}$$

**Ответ:** $\begin{pmatrix}
-1 \\ 
0 \\
1
\end{pmatrix}$.

In [10]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

L = np.array([[1, 0, 0], [11 / 2, 1, 0], [9 / 2, 7 / 3, 1]])
U = np.array([[2, 1, 3], [0, 3 / 2, -23 / 2], [0, 0, 52 / 3]])

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'LU =\n{np.dot(L, U)}\n')

print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

Вектор правой части b =
[ 1 -6 -5]

LU =
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]

Решение x_numpy =
[-1.  0.  1.]


### Задание 4 <a class='anchor' id='system_p2_4'>

*Решите систему линейных уравнений методом Холецкого:*

$$\begin{cases}
81x_1 - 45x_2 + 45x_3 = 531, \\
-45x_1 + 50x_2 - 15x_3 = -460, \\
45x_1 - 15x_2 + 38x_3 = 193.
\end{cases}$$

Матрица системы и вектор правой части имеют вид:

$$A = \begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38
\end{pmatrix}, \; b = \begin{pmatrix}
531 \\ 
-460 \\ 
193
\end{pmatrix}.$$

Элементы матрицы $L$ рассчитываются по формулам:

$$l_{ii}=\sqrt{a_{ii}-\sum_{k = 1}^{i - 1}l_{ik}^{2}},$$
$$l_{ij}=\frac{1}{l_{jj}} \left( a_{ij} - \sum_{k = 1}^{j - 1}l_{ik}l_{jk} \right), \; j < i.$$


Выполним разложение $LL^T$:

$$l_{11} = \sqrt{a_{11}} = \sqrt{81} = 9,$$

$$l_{21} = \frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5,$$

$$l_{31} = \frac{a_{31}}{l_{11}} = \frac{45}{9} = 5,$$

$$l_{22} = \sqrt{a_{22} - l_{21}^2} = \sqrt{50 - 25} = 5,$$

$$l_{32} = \frac{1}{l_{22}} (a_{32} - l_{31} l_{21}) = \frac{1}{5} (-15 + 25) = 2,$$

$$l_{33} = \sqrt{a_{33} - l_{31}^2 - l_{32}^2} = \sqrt{38 - 25 - 4} = 3.$$

Получили матрицу

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, \; L^T = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Теперь решим систему

$$Ly = b,$$

$$\begin{cases}
9y_1 = 531, \\
-5y_1 + 5y_2 = -460, \\
5y_1 + 2y_2 + 3y_3 = 193.
\end{cases} \; \Rightarrow \; \begin{cases}
y_1 = 59, \\
y_2 = \frac{1}{5}(-460 + 5y_1) = \frac{1}{5}(-460 + 295) = -33, \\
y_3 = \frac{1}{3}(193 - 5y_1 - 2y_2) = \frac{1}{3}(193 - 295 + 66) = -12.
\end{cases}$$

Получили:

$$\begin{cases}
y_1 = 59, \\
y_2 = -33, \\
y_3 = -12.
\end{cases}$$

Затем решим систему

$$L^Tx = y,$$

$$\begin{cases}
9x_1 - 5x_2 + 5x_3 = 59, \\
5x_2 + 2x_3 = -33, \\
3x_3 = -12.
\end{cases} \; \Rightarrow \; \begin{cases}
x_3 = -4, \\
x_2 = \frac{1}{5} (-33 - 2x_3) = \frac{1}{5} (-33 + 8) = -5, \\
x_1 = \frac{1}{9} (59 + 5x_2 - 5x_3) = \frac{1}{9} (59 - 25 + 20) = 6.
\end{cases}$$

Получили решение

$$\begin{cases}
x_1 = 6, \\
x_2 = -5, \\
x_3 = -4.
\end{cases}$$

**Ответ:** $\begin{pmatrix}
6 \\ 
-5 \\
-4
\end{pmatrix}$.

In [11]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

L = np.linalg.cholesky(A)

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'L_numpy =\n{L}\n')

print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

Вектор правой части b =
[ 531 -460  193]

L_numpy =
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]

Решение x_numpy =
[ 6. -5. -4.]


### Задание 5 <a class='anchor' id='system_p2_5'>

*Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.*

Общий для всех алгоритмов метод для решения СЛАУ с треугольной матрицей, который будет использоваться при обратном ходе алгоритма.

In [12]:
def solve_triangle(A, b, lower=True):
    """
    Решает СЛАУ с треугольной матрицей.
    A - матрица системы,
    b - правая часть системы,
    lower - если true, то матрица нижнетреугольная, иначе верхнетреугольная.
    """
    size = A.shape[0]
    indexes = range(size) if lower else reversed(range(size))
    
    x = np.zeros(size)
    for i in indexes:
        slice_indexes = slice(i) if lower else slice(size, i, -1)
        x[i] = (b[i] - A[i, slice_indexes] @ x[slice_indexes]) / A[i, i]
        
    return x

#### Метод Холецкого <a class='anchor' id='cholesky'>

Реализуем метод Холецкого.

In [13]:
def solve_cholesky(A, b):
    """
    Решает СЛАУ сетодом Холецкого.
    A - матрица системы,
    b - правая часть системы.
    :return: нижняя треугольная матрица разложения L и решение СЛАУ
    """
    
    if np.linalg.det(A) == 0:
        raise Exception('Определитель матрицы равен 0')
    
    if not np.allclose(A, A.T):
        raise Exception('Матрица несимметричная')
    
    if not all(np.linalg.eigvals(A) > 0):
        raise Exception('Матрица не является положительно определенной')
    
    size = A.shape[0]
    L = np.zeros((size, size))
    for i in range(size):
        for j in range(i + 1):
            L[i, j] = np.sqrt(A[i, i] - L[i, :i] @ L[i, :i]) if i == j else (A[i, j] - L[i, :j] @ L[j, :j]) / L[j, j]
    
    y = solve_triangle(L, b)
    x = solve_triangle(L.T, y, lower=False)
    
    return L, x

При сравнении с решением [Задания 4](#system_p2_4) видно, что решение и полученная матрица $L$ совпадают.

In [14]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

L, x = solve_cholesky(A, b)

print(f'L =\n{L}\n')
print(f'Решение x =\n{x}')

L =
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]

Решение x =
[ 6. -5. -4.]


#### LU - разложение <a class='anchor' id='lu'>

Реализуем $LU$ - разложение.

In [15]:
def solve_lu(A, b):
    """
    Решает СЛАУ сетодом LU-разложения.
    A - матрица системы,
    b - правая часть системы.
    :return: нижняя треугольная и верхняя треугольная матрицы разложения L и U и решение СЛАУ
    """
    
    if np.linalg.det(A) == 0:
        raise Exception('Определитель матрицы равен 0')
    
    size = A.shape[0]
    L = np.zeros((size, size))
    U = np.zeros((size, size))

    U[0, :] = [A[0, j] for j in range(size)]
    L[:, 0] = [A[j, 0] / U[0, 0] for j in range(size)]
    
    for i in range(1, size):
        for j in range(i, size):
            U[i, j] = A[i, j] - L[i, :i] @ U[:i, j]
            L[j, i] = (A[j, i] - L[j, :i] @ U[:i, i]) / U[i, i]
    
    y = solve_triangle(L, b)    
    x = solve_triangle(U, y, lower=False)
    
    return L, U, x

При сравнении с решением [Задания 3](#system_p2_3) видно, что решение и полученные матрицы $L$, $U$ совпадают.

In [16]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

L, U, x = solve_lu(A, b)

print(f'Матрица A =\n{A}\n')
print(f'LU =\n{np.dot(L, U)}\n')

print(f'L =\n{L}\n')
print(f'U =\n{U}\n')

print(f'Решение x =\n{x}')

Матрица A =
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

LU =
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]

L =
[[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]

U =
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]

Решение x =
[-1.  0.  1.]


Сравним также с решением [Задания 4](#system_p2_4).

In [17]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

L, U, x = solve_lu(A, b)

print(f'Матрица A =\n{A}\n')
print(f'LU =\n{np.dot(L, U)}\n')

print(f'L =\n{L}\n')
print(f'U =\n{U}\n')

print(f'Решение x =\n{x}')

Матрица A =
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

LU =
[[ 81. -45.  45.]
 [-45.  50. -15.]
 [ 45. -15.  38.]]

L =
[[ 1.          0.          0.        ]
 [-0.55555556  1.          0.        ]
 [ 0.55555556  0.4         1.        ]]

U =
[[ 81. -45.  45.]
 [  0.  25.  10.]
 [  0.   0.   9.]]

Решение x =
[ 6. -5. -4.]
